apiVersion: v1
kind: Service
metadata:
  name: memberlist
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
    - None
  ipFamilies:
    - IPv4
  ports:
    - name: gossip-tcp
      port: 33333
      protocol: TCP
      targetPort: 33333
    - name: gossip-udp
      port: 33333
      protocol: UDP
      targetPort: 33333
    - name: api
      port: 4396
      protocol: TCP
      targetPort: 4396
  selector:
    app: memberlist
  sessionAffinity: None
  type: ClusterIP